<?php
/**
 * @file
 * Custom functions for Views Bootstrap.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\dardev_table\ViewsTable;
use Drupal\views\ViewExecutable;
/**
 * Implements hook_theme().
 */

function dardev_table_theme($existing, $type, $theme, $path) {
  return [
    'dardev_table_theme' => [
      'variables' => ['rows' => [], 'header' => [], 'attributes' => []],
    ],
  ];
}


function dardev_table_views_pre_render(ViewExecutable $view) {

  if (isset($view) && ($view->style_plugin->definition['id'] == 'views_table') ){
    
    $view->element['#attached']['library'][] = 'dardev_table/dardev_table';
    }
  
}


 

function dardev_table_preprocess(&$variables) {
  $variables['lang'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $lang_code         = \Drupal::languageManager()->getCurrentLanguage()->getId();
 }