<?php

use Drupal\taxonomy\Entity\Term;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;

function md_manager_theme($existing, $type, $theme, $path)
{
  return [
    'footer_menu' => [
      'variables' => [
        'menu' => NULL
      ],
    ],
    'social_links' => [
      'variables' => [
        'social' => NULL
      ],
    ],
    'organigramme' => [
      'variables' => [
        'currentLang' => NULL,
        'content' => NULL
      ],
    ],
    'organigramme_block' => [
      'variables' => [
        'currentLang' => NULL,
        'content' => NULL
      ],
    ],

    'timeline' => [
      'variables' => [
        'timeLines' => NULL,
        'data' => NULL
      ],
    ],
    'human_resources' => [
      'variables' => [
        'humanResources' => NULL,
        'data' => NULL,
      ],
    ],
    'states' => [
      'variables' => [
        'paths' => NULL,
        'data' => NULL,
        'title' => NULL,
        'body' => NULL,
        'description'=> NULL,
      ],
    ],
    'top_bar' => [
      'variables' => [
        'contact' => NULL
      ],
    ],
    'footer_contact' => [
      'variables' => [
        'contact' => NULL
      ],
    ],
  ];
}

/**
 * Implements hook_views_query_alter().
 */
function md_manager_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {
  if ($view->id() == 'project') {
    $term = \Drupal::routeMatch()->getParameter('taxonomy_term');
    if ($term instanceof Term) {
      $term_id = $term->id();
    }
    if (!empty($term_id)) {
      $query->addTable("node__field_project_type");
      $query->addWhere(1, "node__field_project_type.field_project_type_target_id", $term->id(), '=');
    }
  }
}
